require 'rspec'
require_relative '../lib/record'
require_relative '../lib/parser'
require_relative '../lib/record_reader'
require_relative '../lib/record_writer'
require_relative '../lib/record_system'